---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-backtest-anomaly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/stock-backtest-anomaly.git
    targetRevision: main
    path: charts/stock-backtest-anomaly
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
